twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
       categories_g: '@App\Repository\CategoryRepository'
       TotalPriceCart: '@App\Model\Cart'

when@test:
    twig:
        strict_variables: true
